version: '3.3'

services:

  api:
    image: node:latest
    volumes:
    - ./api:/var/www/api
    working_dir: /var/www/api
    ports:
    - "1488:1488"
    tty: true
    command: npm start

  frontend:
    image: node:latest
    volumes:
    - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    ports:
    - "8083:8080"
    tty: true
    command: npm run serve